Revamp UI admin
ivanms1/project-shelf pull request #140
Opened 2023-02-19 06:19 UTC by revengemiroz

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Showcase

Please attach a picture or a video showing what this change does.

2023-02-19 08:17 UTC, rohilpinto commented on apps/admin/src/pages/Home/index.tsx
> +      {/*
can you

2023-02-19 08:25 UTC, rohilpinto requested changes
Requesting some comment deletions

2023-02-19 08:25 UTC, rohilpinto commented on apps/admin/src/pages/Home/index.tsx
> +// import { useGetAllProjectsQuery } from 'apollo-hooks';
could you please delete this comment

2023-02-19 08:25 UTC, rohilpinto commented on apps/admin/src/pages/Home/index.tsx
> +  // const { data } = useGetAllProjectsQuery();
could you please delete this comment

2023-02-19 08:25 UTC, rohilpinto commented on apps/admin/src/pages/Home/index.tsx
> +      </div> */}
could you please delete this comment

2023-02-28 06:23 UTC, revengemiroz commented on apps/admin/src/pages/Home/index.tsx
> +      </div> */}
done

2023-02-28 06:23 UTC, revengemiroz commented on apps/admin/src/pages/Home/index.tsx
> +  // const { data } = useGetAllProjectsQuery();
done

2023-02-28 06:23 UTC, revengemiroz commented on apps/admin/src/pages/Home/index.tsx
> +// import { useGetAllProjectsQuery } from 'apollo-hooks';
done

2023-02-28 06:54 UTC, ivanms1 approved these changes
LGTM

2023-02-28 06:55 UTC, merged